version: '3'
services:
  nginx:
    build: ./nginx/
    ports:
      - "3000:3000"
    volumes:
      # app
      - /home/myweb/yf-local:/home/myweb/yf-local
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # ca 
      # passord 123456
      - ./nginx/ca/server.crt:/etc/nginx/server.crt:ro
      - ./nginx/ca/server.key:/etc/nginx/server.key:ro
    links:
      - fpm:__DOCKER_PHP_FPM__
    restart: always

  # php-fpm
  fpm:
    container_name: fpm
    build:
        context: ./php/
        dockerfile: Dockerfile     
    ports:
      - "9000"
    volumes:
      # app
      - /home/myweb/yf-local:/home/myweb/yf-local
      - ./php/app.json:/home/myweb/app.json
      - ./php/pulsarNode.sh:/home/myweb/pulsarNode.sh
      # php.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql:mysql
      - redis:redis
      - pulsar:pulsar
    restart: always

  # database
  mysql:
    build: ./mysql/
    ports:
      - "3306:3306"
    command: --init-file /opt/mysql/yf_gateway.sql
    volumes:
      - ./mysql/:/opt/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=yf_gateway
    restart: always

  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass 123456"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  #pulsar
  pulsar:
    build: ./pulsar/
    hostname: pulsar
    command: bin/pulsar standalone
    volumes:
      - ./pulsar/client.token:/opt/client.token
      - ./pulsar/my-secret.key:/opt/my-secret.key
      - ./pulsar/docker_pulsar_create.sh:/opt/docker_pulsar_create.sh
      - ./pulsar/standalone.conf:/pulsar/conf/standalone.conf
      - ./pulsar/client.conf:/pulsar/conf/client.conf
      - ./pulsar/functions_worker.yml:/pulsar/conf/functions_worker.yml
    ports:
      - 6650:6650
      - 8080:8080
    restart: always

  #pulsar_manager
  pulsar_manager:
    build: ./pulsar_manager/
    volumes:
      - ./pulsar_manager/application.properties:/pulsar-manager/pulsar-manager/application.properties
      - ./pulsar/client.token:/opt/client.token
      - ./opt/pulsar/my-secret.key:/opt/my-secret.key
    ports:
      - 9527:9527
      - 7750:7750
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
    depends_on:
      - pulsar
    links:
      - pulsar:pulsar
    restart: always
